version: '3'
services:
  web:
    build: .

    command: python app.py --host 0.0.0.0

    ports:
      - "8015:5000"
    env_file:
      - .env

  db:
    image: postgres:13
    ports:
      - "8016:5432"
    environment:
      POSTGRES_DB: dfg
      POSTGRES_USER: dfg
      POSTGRES_PASSWORD: dfg
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
volumes:
  postgres_data:
